### ISSUE TITLE
Several broken symlinks when building

### ISSUE THREAD

**Issue by edelvalle** [wfpaisa/plane-icon-theme#1]
I think you have several references to icons in your local computer that are not present in the repo:

Ex: `plane-icon-theme/src/plane-dark/apps/scalable/com.gexperts.Tilix.svg -> /home/Proyectos/plane-mono-dark/apps/48/tilix.svg`

Like this one several of them and that does not allow the project to be built in another computer. I guess this happen because the symlinks have absolute paths, try using relative paths.

**Comment by wfpaisa** [comment]
Thank you, fixed.
