### ISSUE TITLE
Missing picon?

### ISSUE THREAD

**Issue by sgse** [wfpaisa/plane-icon-theme#2]
Hi,
I use your nice picon set, missing picon are 
> gtk-icon-theme-error-quark: Symbol »emblem-synchronized« nicht im Thema plane-dark vorhanden (0)
> gtk-icon-theme-error-quark: Symbol »preferences-desktop-multimedia« nicht im Thema plane-dark vorhanden (0)
> gtk-icon-theme-error-quark: Symbol »sync-error« nicht im Thema plane-dark vorhanden (0)
> gtk-icon-theme-error-quark: Symbol »sync-synchronizing« nicht im Thema plane-dark vorhanden (0)
> gtk-icon-theme-error-quark: Symbol »system-reboot« nicht im Thema plane-dark vorhanden (0)
Thx a lot :-) for your perfect work.

**Comment by wfpaisa** [comment]
Hi sgse, can you please tell me what application uses them?
I need to know so I can see the changes in their design.
Greetings
