### ISSUE TITLE
Screenshot-icon not displayed correctly on Mate

### ISSUE THREAD

**Issue by Vittelius** [wfpaisa/plane-icon-theme#4]
![bildschirmfoto zu 2018-02-10 18-47-57](https://user-images.githubusercontent.com/3718818/36064968-dce52370-0e93-11e8-833d-7fa0940e77cc.png)
As you can see in the screenshot, the screenshot-tools icon is not displayed correctly. The scissor is supposed to be on top.

OS: Solus
DE: Mate 1.20

**Comment by wfpaisa** [comment]
I want to give support in future versions, for now just Gnome :)
