### ISSUE TITLE
Make theme distribution- and desktop-agnostic

### ISSUE THREAD

**Issue by Vittelius** [wfpaisa/plane-icon-theme#5]
The theme features some Manjaro-branding which doesn't really make sense on non-Manjaro-systems like my Solus install:
![bildschirmfoto zu 2018-02-10 19-11-20](https://user-images.githubusercontent.com/3718818/36065097-3699515a-0e96-11e8-93a6-67c32f4571a0.png)
I also had to rename some icons to make them usable. This is due to Mate shipping there own (mostly forked) applications like pluma (gedit). Usually icon-themes have a lot of symlinks to compensate for this.

**Comment by wfpaisa** [comment]
can you tell me, what symbolic links are necessary to create.
Eg: gedit.svg -> pluma.svg, x.svg -> x2.svg

**Comment by wfpaisa** [comment]
Done in the last version
