### ISSUE TITLE
Missing ubuntu icons

### ISSUE THREAD

**Issue by dcabrejas** [wfpaisa/plane-icon-theme#6]
Hi, thanks for the theme, I really like it. There are some missing ubuntu icons which a think will make it even better, for instance Rhythm-box, Archive Manager, Software,  Files, Contacts and Transmission. Are there any plans to add those as well? 

Thanks again.

**Comment by wfpaisa** [comment]
Hi @dcabrejas of course they enter in my next version ;)

**Comment by dcabrejas** [comment]
Gracias! will keep an eye out for it. Keep up the good work :)
