### ISSUE TITLE
Request Eclipse Icon

### ISSUE THREAD

**Issue by btd1337** [wfpaisa/plane-icon-theme#7]
Could you create an icon for Eclipse IDE?

![eclipse](https://user-images.githubusercontent.com/11943860/46922529-b28cdc80-cfe0-11e8-9aec-0091161d3599.png)

**Comment by wfpaisa** [comment]
Add in the next version, ;)
https://github.com/wfpaisa/plane-icon-theme/blob/master/src/variants/Plane/apps/eclipse.svg
