### ISSUE TITLE
[Icon Request] Mimetypes: c#   - *.cs, *.csproj; *.js; *.css 

### ISSUE THREAD

**Issue by ceyhunn** [wfpaisa/plane-icon-theme#9]
C#:
![iconfinder_c _84437](https://user-images.githubusercontent.com/5506156/50050517-e8e8f400-0116-11e9-880b-b93887002e08.png)
Javascript:
![iconfinder_javascript_84685](https://user-images.githubusercontent.com/5506156/50050520-fa320080-0116-11e9-93b3-8a74018723d1.png)
Css:
![iconfinder_file__css__web__3209606](https://user-images.githubusercontent.com/5506156/50050536-76c4df00-0117-11e9-8562-877f1c12b256.png)

**Comment by wfpaisa** [comment]
This is a characteristics I have been thinking since some time, because demand design and development a template for each extension. I gonna think in something but this could take some time to develop. :)
